FROM node:20

# Устанавливаем сборочные инструменты
RUN apt-get update && apt-get install -y python3 g++ make

WORKDIR /app

COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]

