version: '3.9'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    container_name: studybuddy_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - db
      
  frontend:
    build: 
      context: ./frontend
    container_name: studybuddy_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
    env_file:
      - ./frontend/.env

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: studybuddy_db
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: