version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    container_name: studybuddy_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
      - /app/node_modules

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: studybuddy_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: studybuddy_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
  uploads_data: