# Stage 1: сборка фронта
FROM node:20-bullseye AS frontend-build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend ./
RUN npm run build

# Stage 2: продовый бекенд
FROM node:20-bullseye
WORKDIR /app

# Копируем backend
COPY backend/package*.json ./
RUN npm install --production
COPY backend/src ./src

# Копируем готовый фронт
COPY --from=frontend-build /app/dist ./frontend

EXPOSE 3000
ENV MODE=production

CMD ["node", "src/server.js"]